### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by nadeau** [ripienaar/mcollective-agent-debugger#1]
$ ./mc-debugger 
./mc-debugger:73:in `setup': uninitialized constant MCollective::Logger::Console_logger (NameError)
        from ./mc-debugger:190
        from ./mc-debugger:24:in`consolize'
        from ./mc-debugger:176

I'm running debian testing packaged mc (1.2.1+dfsg-2)

**Comment by ripienaar** [comment]
The debugger will probably only work on 2.0.x now
